### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by shibu5555** [dinosaurfiles/cybrary-video-downloader#10]
after login it is showing that certificate verify failed.....please fixed this
![screenshot from 2017-09-27 17-24-33](https://user-images.githubusercontent.com/22362769/30912174-2d98f9b4-a3a9-11e7-8c58-b9495a7a9b5c.png)

**Comment by dinosaurfiles** [comment]
Hi @shibu5555! Unfortunately there is nothing wrong with the code. The error you're experiencing is due to your internet connection **not resolving SSL certificates completely**. Proof of my test: 
![screenshot_2017-10-08_23-07-25](https://user-images.githubusercontent.com/10389490/31318065-a5b6b192-ac7e-11e7-9a89-4508075652a0.png)

As you can see it's working fine for me.

I have a solution but it would require to not use SSL at all and would make both your connection and future users of cybrary-video-downloader connection insecure per this [conversation](https://stackoverflow.com/a/34503805).

**Comment by dinosaurfiles-zz** [comment]
Hi again @shibu5555, I've added a quick option for you, just append the `-ssl False` option. Ex: `python --quality 360 --course "course link" --ssl False`. If another error pops up, please feel free to open another issue. Thank you!

**Comment by shibu5555** [comment]
now working for me sir....​
 Screenshot from 2017-10-08 22-13-36.png
<https://drive.google.com/file/d/0B_9idj4p7FVXTUFGd1NKdW5JSGc/view?usp=drive_web>
​

**Comment by shibu5555** [comment]
What to do now sir...?

**Comment by dinosaurfiles-zz** [comment]
Hi again @shibu5555, it seems like your error doesn't concern cybrary-video-downloader. The error may be likely on your installation of `youtube-dl` with a similar issue [here](https://github.com/rg3/youtube-dl/issues/883).

Anyways, please do the following:
- [ ] Uninstall `youtube-dl` by `apt-get remove youtube-dl`
- [ ] Install `youtube-dl` *again* by:
    `sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`
    `sudo chmod a+rx /usr/local/bin/youtube-dl`

    or 

    `sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl`
    `sudo chmod a+rx /usr/local/bin/youtube-dl`

**Comment by shibu5555** [comment]
great sir.....its work....u r really awesome.........

**Comment by dinosaurfiles-zz** [comment]
Glad I could help! Don't forget to star ⭐️ the repo and share it to your friends!

**Comment by shibu5555** [comment]
Sure sir

**Comment by shibu5555** [comment]
sir i want the video lectures of offensive security course.....do u have
any idea from where i can get that for free....its very important....

**Comment by dinosaurfiles-zz** [comment]
I definitely recommend you [r/netsec](https://www.reddit.com/r/netsec/) and its [Getting Started in Information Security guide](https://www.reddit.com/r/netsec/wiki/start). Select a category/specialty and you're good to go! 😄
