### ISSUE TITLE
downloading is not working

### ISSUE THREAD

**Issue by NobodyLR** [dinosaurfiles/cybrary-video-downloader#4]
hello

you must select an outpud directory for youtube-dl for it to start downloading

**Comment by dinosaurfiles** [comment]
Hi @NobodyLR ! I've tested the program and it runs as expected but with error warnings such as SNIMissingWarning, etc due to the fact that I used Python 2.7 mainly for development. I could also add a feature in which I can set the folder output if that is what you want.

Please also comment your python version by simply typing `python --version`
